/**
 * Mock Dataset for Geo-Vision
 * City: Coimbatore, Tamil Nadu
 */

export const INITIAL_TICKETS = [
  {
    id: "GV-CBE-8801",
    title: "Deep Road Cave-in / Pothole",
    category: "POTHOLE",
    categoryLabel: "Pothole & Road Damage",
    department: "Coimbatore Roads & Infrastructure Dept",
    severityScore: 92,
    severityLabel: "Critical",
    confidence: 0.96,
    estimatedDepthCm: 18,
    estimatedAreaSqM: 3.2,
    status: "Pending",
    citizenImpactCount: 6,
    reportedAt: "2026-08-20T08:15:00Z",
    citizenName: "Karthik R. (Gandhipuram)",
    citizenPhone: "+91 9876543210",
    location: {
      lat: 11.0168,
      lng: 76.9558,
      address: "Cross Cut Road Signal, Gandhipuram Zone 2 (Central), Coimbatore",
      ward: "Ward 42",
    },
    beforeImage: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80",
    imageHash: "a1b2c3d4e5f67890",
    gradCamData: {
      centerX: 48,
      centerY: 52,
      radius: 28,
      intensity: 0.94,
      hotspots: [
        { x: 48, y: 52, val: 0.95 },
        { x: 55, y: 58, val: 0.88 },
      ],
      layerName: "ConvLayer_4_ResNet",
    },
    history: [
      { timestamp: "2026-08-20T08:15:00Z", action: "Report Submitted", actor: "Citizen (Karthik R.)" },
      { timestamp: "2026-08-20T08:15:02Z", action: "CV Triaged: Severity 92/100 (Critical)", actor: "Geo-Vision CV Engine" },
      { timestamp: "2026-08-20T08:15:03Z", action: "Geo-Routed to Coimbatore Roads & Infrastructure Dept", actor: "Geo-Routing Engine" },
      { timestamp: "2026-08-20T08:40:00Z", action: "+5 Duplicate Citizens Merged (Impact Counter: 6)", actor: "Spatial Duplicate Cluster" },
    ],
  },
  {
    id: "GV-CBE-8802",
    title: "Major Water Pipeline Burst",
    category: "WATER_LEAK",
    categoryLabel: "Water Pipeline Leakage / Pipe Burst",
    department: "Coimbatore City Metro Water Board",
    severityScore: 88,
    severityLabel: "Critical",
    confidence: 0.98,
    estimatedDepthCm: null,
    estimatedAreaSqM: 8.5,
    status: "In Progress",
    assignedOfficer: "Officer Subramaniam V. (ID: CBE-W-402)",
    citizenImpactCount: 11,
    reportedAt: "2026-08-20T06:30:00Z",
    citizenName: "Priya S. (Peelamedu)",
    citizenPhone: "+91 9840123456",
    location: {
      lat: 11.0285,
      lng: 76.9950,
      address: "Avinashi Road, Near PSG Tech, Peelamedu Zone 3, Coimbatore",
      ward: "Ward 38",
    },
    beforeImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&auto=format&fit=crop&q=80",
    imageHash: "f9e8d7c6b5a43210",
    gradCamData: {
      centerX: 42,
      centerY: 45,
      radius: 32,
      intensity: 0.91,
      hotspots: [{ x: 42, y: 45, val: 0.98 }],
      layerName: "ConvLayer_4_ResNet",
    },
    history: [
      { timestamp: "2026-08-20T06:30:00Z", action: "Report Submitted", actor: "Citizen (Priya S.)" },
      { timestamp: "2026-08-20T07:05:00Z", action: "Assigned to Officer Subramaniam V.", actor: "Dept Dispatch" },
    ],
  },
  {
    id: "GV-CBE-8803",
    title: "Overflowing Garbage Dump Site",
    category: "SANITATION",
    categoryLabel: "Garbage Dump & Sanitation",
    department: "Coimbatore Solid Waste Management",
    severityScore: 64,
    severityLabel: "Moderate",
    confidence: 0.91,
    estimatedDepthCm: null,
    estimatedAreaSqM: 5.0,
    status: "Pending",
    citizenImpactCount: 3,
    reportedAt: "2026-08-20T07:45:00Z",
    citizenName: "Anand M. (RS Puram)",
    citizenPhone: "+91 9790112233",
    location: {
      lat: 11.0100,
      lng: 76.9450,
      address: "DB Road Commercial Junction, RS Puram Zone 1 (West), Coimbatore",
      ward: "Ward 23",
    },
    beforeImage: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=600&auto=format&fit=crop&q=80",
    imageHash: "b5c6d7e8f9012345",
    gradCamData: {
      centerX: 55,
      centerY: 60,
      radius: 25,
      intensity: 0.85,
      hotspots: [{ x: 55, y: 60, val: 0.91 }],
      layerName: "ConvLayer_4_ResNet",
    },
    history: [
      { timestamp: "2026-08-20T07:45:00Z", action: "Report Submitted", actor: "Citizen (Anand M.)" },
    ],
  },
  {
    id: "GV-CBE-8804",
    title: "Exposed Underground Electrical Wires",
    category: "ELECTRICAL",
    categoryLabel: "Streetlight & Electrical Hazard",
    department: "TANGEDCO & Coimbatore Lighting",
    severityScore: 95,
    severityLabel: "Critical",
    confidence: 0.97,
    estimatedDepthCm: null,
    estimatedAreaSqM: 1.2,
    status: "In Progress",
    assignedOfficer: "Officer Ganesan K. (ID: CBE-E-109)",
    citizenImpactCount: 8,
    reportedAt: "2026-08-20T05:10:00Z",
    citizenName: "Divya N. (Ukkadam)",
    citizenPhone: "+91 9884567890",
    location: {
      lat: 10.9920,
      lng: 76.9620,
      address: "Ukkadam Bus Stand Entrance, Zone 4 (South), Coimbatore",
      ward: "Ward 78",
    },
    beforeImage: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=600&auto=format&fit=crop&q=80",
    imageHash: "c1d2e3f4a5b67890",
    gradCamData: {
      centerX: 40,
      centerY: 38,
      radius: 22,
      intensity: 0.96,
      hotspots: [{ x: 40, y: 38, val: 0.99 }],
      layerName: "ConvLayer_4_ResNet",
    },
    history: [
      { timestamp: "2026-08-20T05:10:00Z", action: "Report Submitted", actor: "Citizen (Divya N.)" },
      { timestamp: "2026-08-20T05:15:00Z", action: "Flagged High Safety Hazard (95/100 Critical)", actor: "CV Safety Guard" },
    ],
  },
  {
    id: "GV-CBE-8798",
    title: "Fallen Tree Blocking Road",
    category: "FALLEN_TREE",
    categoryLabel: "Fallen Tree & Storm Debris",
    department: "Coimbatore Parks & Forestry Dept",
    severityScore: 78,
    severityLabel: "Critical",
    confidence: 0.94,
    estimatedDepthCm: null,
    estimatedAreaSqM: 12.0,
    status: "Resolved",
    assignedOfficer: "Officer Murugan M. (ID: CBE-P-204)",
    citizenImpactCount: 4,
    reportedAt: "2026-08-19T14:20:00Z",
    resolvedAt: "2026-08-19T17:45:00Z",
    citizenName: "Ramesh K. (Saibaba Colony)",
    location: {
      lat: 11.0260,
      lng: 76.9410,
      address: "NSR Road, Saibaba Colony Zone 1, Coimbatore",
      ward: "Ward 15",
    },
    beforeImage: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=600&auto=format&fit=crop&q=80",
    afterImage: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&auto=format&fit=crop&q=80",
    resolutionVerification: {
      verified: true,
      matchScore: 0.94,
      clearanceScore: 0.92,
      visualMatchPercent: 92,
      verifiedAt: "2026-08-19T17:45:02Z",
      reasoning: "Resolution Verified: CV engine confirmed 0% issue residue (92% site clearance). Road unblocked.",
    },
    history: [
      { timestamp: "2026-08-19T14:20:00Z", action: "Report Submitted", actor: "Citizen (Ramesh K.)" },
      { timestamp: "2026-08-19T17:40:00Z", action: "After-Photo Uploaded", actor: "Officer Murugan M." },
      { timestamp: "2026-08-19T17:45:00Z", action: "CV Verified Resolution (92% Match)", actor: "CV Resolution Verification Loop" },
    ],
  },
];

export const HOTSPOT_PREDICTIONS = [
  {
    id: "HOT-CBE-01",
    zone: "Gandhipuram Signal & Cross Cut Corridor",
    category: "POTHOLE",
    department: "Coimbatore Roads & Infrastructure Dept",
    recurrenceCount: 16,
    riskScore: 93,
    riskLevel: "High Risk",
    reason: "Heavy bus transit + monsoon runoff causing repeated asphalt sub-base breakdown.",
    recommendedAction: "Schedule full sub-surface re-asphalting and reinforced storm drain trenching.",
    location: { lat: 11.0168, lng: 76.9558 },
  },
  {
    id: "HOT-CBE-02",
    zone: "Avinashi Road Peelamedu Section",
    category: "WATER_LEAK",
    department: "Coimbatore City Metro Water Board",
    recurrenceCount: 11,
    riskScore: 86,
    riskLevel: "High Risk",
    reason: "Aging 25-year cast iron feeder main joint pressure bursts under peak pumping hours.",
    recommendedAction: "Proactive replacement of 180m main pipeline section with HDPE piping.",
    location: { lat: 11.0285, lng: 76.9950 },
  },
  {
    id: "HOT-CBE-03",
    zone: "RS Puram Commercial Market Sector",
    category: "SANITATION",
    department: "Coimbatore Solid Waste Management",
    recurrenceCount: 19,
    riskScore: 78,
    riskLevel: "Medium High",
    reason: "Commercial vegetable and retail vendor dumping exceeding bin capacity.",
    recommendedAction: "Deploy 2 additional automated compactors and double clearance frequency.",
    location: { lat: 11.0100, lng: 76.9450 },
  },
  {
    id: "HOT-CBE-04",
    zone: "Ukkadam Bus Stand Approach",
    category: "ELECTRICAL",
    department: "TANGEDCO & Coimbatore Lighting",
    recurrenceCount: 8,
    riskScore: 71,
    riskLevel: "Medium",
    reason: "Low-hanging overhead service cables near flyover construction zone.",
    recommendedAction: "Underground cable ducting conversion.",
    location: { lat: 10.9920, lng: 76.9620 },
  },
];

export const ACCOUNTABILITY_LEADERBOARD = {
  departments: [
    {
      name: "Coimbatore Roads & Infrastructure",
      totalTickets: 156,
      resolvedTickets: 142,
      verifiedResolutions: 138,
      verifiedRate: 97.1,
      avgTurnaroundHrs: 4.0,
      auditFlags: 2,
    },
    {
      name: "Coimbatore City Metro Water Board",
      totalTickets: 104,
      resolvedTickets: 92,
      verifiedResolutions: 88,
      verifiedRate: 95.6,
      avgTurnaroundHrs: 3.6,
      auditFlags: 1,
    },
    {
      name: "Coimbatore Parks & Forestry",
      totalTickets: 72,
      resolvedTickets: 68,
      verifiedResolutions: 66,
      verifiedRate: 97.0,
      avgTurnaroundHrs: 2.3,
      auditFlags: 0,
    },
    {
      name: "Coimbatore Solid Waste Management",
      totalTickets: 230,
      resolvedTickets: 208,
      verifiedResolutions: 194,
      verifiedRate: 93.2,
      avgTurnaroundHrs: 1.7,
      auditFlags: 3,
    },
    {
      name: "TANGEDCO & Coimbatore Lighting",
      totalTickets: 82,
      resolvedTickets: 77,
      verifiedResolutions: 75,
      verifiedRate: 97.4,
      avgTurnaroundHrs: 2.0,
      auditFlags: 1,
    },
  ],
  officers: [
    {
      id: "OFF-CBE-101",
      name: "Officer Murugan M.",
      department: "Coimbatore Parks & Forestry",
      resolvedCount: 45,
      verifiedCount: 44,
      verifiedRate: 97.8,
      avgHrs: 2.0,
      auditFlags: 0,
      badge: "⭐ Top Verified Resolver (CBE)",
    },
    {
      id: "OFF-CBE-102",
      name: "Officer Ganesan K.",
      department: "TANGEDCO & Lighting",
      resolvedCount: 41,
      verifiedCount: 40,
      verifiedRate: 97.5,
      avgHrs: 2.2,
      auditFlags: 0,
      badge: "⚡ Safety Excellence",
    },
    {
      id: "OFF-CBE-103",
      name: "Officer Subramaniam V.",
      department: "Coimbatore Water Board",
      resolvedCount: 38,
      verifiedCount: 36,
      verifiedRate: 94.7,
      avgHrs: 3.4,
      auditFlags: 1,
      badge: "💧 Rapid Response",
    },
  ],
};
